<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.0 on win32)" generated="20210205 10:51:18.751" rpa="false">
<suite id="s1" name="TesteBlogTest" source="C:\Robotframework\QArentenaBlogTest\TesteBlogTest.robot">
<test id="s1-t1" name="Caso de Teste 01: Pesquisar um post">
<kw name="Acessar a pÃ¡gina do blog" library="ResourceBlogTest">
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>url=${URL}</arg>
<arg>browser=${BROWSER}</arg>
</arguments>
<msg timestamp="20210205 10:51:18.983" level="INFO">Opening browser 'Chrome' to base url 'http://robotizandotestes.blogspot.com/'.</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20210205 10:52:13.842" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<status status="PASS" starttime="20210205 10:52:13.842" endtime="20210205 10:52:13.842"></status>
</kw>
<msg timestamp="20210205 10:52:13.850" level="FAIL">WebDriverException: Message: unknown error: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
</msg>
<status status="FAIL" starttime="20210205 10:51:18.983" endtime="20210205 10:52:13.850"></status>
</kw>
<status status="FAIL" starttime="20210205 10:51:18.983" endtime="20210205 10:52:13.854"></status>
</kw>
<status status="FAIL" starttime="20210205 10:51:18.982" endtime="20210205 10:52:13.856" critical="yes">WebDriverException: Message: unknown error: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
</status>
</test>
<status status="FAIL" starttime="20210205 10:51:18.752" endtime="20210205 10:52:13.860"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TesteBlogTest">TesteBlogTest</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210205 10:51:18.785" level="ERROR">Error in file 'C:\Robotframework\QArentenaBlogTest\ResourceBlogTest.robot' on line 9: Invalid variable name '${BTN_PESQUISAR} css=button.search-expand.touch-icon-button'.</msg>
<msg timestamp="20210205 10:51:18.786" level="ERROR">Error in file 'C:\Robotframework\QArentenaBlogTest\ResourceBlogTest.robot' on line 11: Invalid variable name '${INPUT_PESQUISAR} name=q'.</msg>
<msg timestamp="20210205 10:51:18.786" level="ERROR">Error in file 'C:\Robotframework\QArentenaBlogTest\ResourceBlogTest.robot' on line 13: Invalid variable name '${SUBMIT_PESQUISAR} input.search-action.flat-button'.</msg>
</errors>
</robot>
